### ISSUE TITLE
"Malformed HTTP Status Code: 5"

### ISSUE THREAD

**Issue by bcongdon** [acm-uiuc/groot-merch-service#17]
We're seeing this entry in the merch service logs:
`2017/09/08 13:57:51 Get http://groot-merch-service:6969/merch/users/bcongdo2: malformed HTTP status code "5"`

This causes the credits to display as 0, and the user pin to not be displayed when viewing the credits panel in the intranet.

Originally reported as https://github.com/acm-uiuc/groot-credits-service/issues/11

**Comment by sameetandpotatoes** [comment]
Merged and resolved by testing on UI. Closing
